using ConcordiaCurriculumManager.DTO.Courses;
using ConcordiaCurriculumManager.DTO.Dossiers.CourseRequests.InputDTOs;
using ConcordiaCurriculumManager.Filters.Exceptions;
using ConcordiaCurriculumManager.Models.Curriculum;
using ConcordiaCurriculumManager.Models.Curriculum.Dossiers;
using ConcordiaCurriculumManager.Models.Users;
using ConcordiaCurriculumManager.Repositories;

namespace ConcordiaCurriculumManager.Services;

public interface ICourseService
{
    public IEnumerable<CourseCareerDTO> GetAllCourseCareers();
    public IEnumerable<CourseComponentDTO> GetAllCourseComponents();
    public Task<IEnumerable<string>> GetAllCourseSubjects();
    public Task<CourseCreationRequest> InitiateCourseCreation(CourseCreationInitiationDTO initiation, Guid userId);
    public Task<CourseModificationRequest> InitiateCourseModification(CourseModificationInitiationDTO modification, Guid userId);
    public Task<CourseDeletionRequest> InitiateCourseDeletion(CourseDeletionInitiationDTO deletion, Guid userId);
    public Task<Course?> GetCourseData(string subject, string catalog);
    public Task<CourseCreationRequest?> EditCourseCreationRequest(EditCourseCreationRequestDTO edit);
    public Task<CourseModificationRequest?> EditCourseModificationRequest(EditCourseModificationRequestDTO edit);
    public Task DeleteCourseCreationRequest(Guid courseRequestId);
    public Task DeleteCourseModificationRequest(Guid courseRequestId);
}

public class CourseService : ICourseService
{
    private readonly ILogger<CourseService> _logger;
    private readonly ICourseRepository _courseRepository;
    private readonly IDossierService _dossierService;
    private readonly IDossierRepository _dossierRepository;

    public CourseService(ILogger<CourseService> logger, ICourseRepository courseRepository, IDossierService dossierService, IDossierRepository dossierRepository)
    {
        _logger = logger;
        _courseRepository = courseRepository;
        _dossierService = dossierService;
        _dossierRepository = dossierRepository;
    }

    public IEnumerable<CourseCareerDTO> GetAllCourseCareers()
    {
        var list = new List<CourseCareerDTO>();
        foreach (int career in Enum.GetValues(typeof(CourseCareerEnum)))
        {
            var careerEnum = (CourseCareerEnum)career;
            list.Add(new CourseCareerDTO { CareerCode = careerEnum, CareerName = careerEnum.ToString() });
        }

        return list;
    }

    public IEnumerable<CourseComponentDTO> GetAllCourseComponents()
    {
        var componentsList = new List<CourseComponentDTO>();
        foreach (var mapping in ComponentCodeMapping.GetComponentCodeMapping().ToList())
        {
            componentsList.Add(new CourseComponentDTO { ComponentCode = mapping.Key, ComponentName = mapping.Value });
        }

        return componentsList;
    }

    public async Task<IEnumerable<string>> GetAllCourseSubjects()
    {
        return await _courseRepository.GetUniqueCourseSubjects();
    }

    public async Task<CourseCreationRequest> InitiateCourseCreation(CourseCreationInitiationDTO initiation, Guid userId)
    {
        var exists = await _courseRepository.GetCourseBySubjectAndCatalog(initiation.Subject, initiation.Catalog) is not null;
        if (exists)
        {
            throw new BadRequestException("The course already exists");
        }

        Dossier dossier = await _dossierService.GetDossierForUserOrThrow(initiation.DossierId, userId);

        var course = Course.CreateCourseFromDTOData(initiation, (await _courseRepository.GetMaxCourseId()) + 1, 1);

        await SaveCourseForUserOrThrow(course, userId);

        var courseCreationRequest = new CourseCreationRequest 
        {
            Id = Guid.NewGuid(),
            NewCourseId = course.Id,
            DossierId = dossier.Id,
            Rationale = initiation.Rationale,
            ResourceImplication = initiation.ResourceImplication,
            Comment = initiation.Comment,
            Conflict = "Autogenerated comment" // TODO: Correctly autogenerate comment to indicate potential issues
        };

        await _dossierService.SaveCourseCreationRequest(courseCreationRequest);

        return courseCreationRequest;
    }

    public async Task<CourseModificationRequest> InitiateCourseModification(CourseModificationInitiationDTO modification, Guid userId)
    {
        var oldCourse = await _courseRepository.GetCourseByCourseId(modification.CourseId) ?? throw new NotFoundException("The course does not exist.");

        Dossier dossier = await _dossierService.GetDossierForUserOrThrow(modification.DossierId, userId);

        var newModifiedCourse = Course.CreateCourseFromDTOData(modification, oldCourse.CourseID, oldCourse.Version + 1);

        await SaveCourseForUserOrThrow(newModifiedCourse, userId);

        var courseModificationRequest = new CourseModificationRequest
        {
            Id = Guid.NewGuid(),
            CourseId = newModifiedCourse.Id,
            DossierId = dossier.Id,
            Rationale = modification.Rationale,
            ResourceImplication = modification.ResourceImplication,
            Comment = modification.Comment,
            Conflict = "Autogenerated comment" // TODO: Correctly autogenerate comment to indicate potential issues
        };

        await _dossierService.SaveCourseModificationRequest(courseModificationRequest);

        return courseModificationRequest;
    }

    public async Task<Course?> GetCourseData(string subject, string catalog)
    {
        var course = await _courseRepository.GetCourseBySubjectAndCatalog(subject, catalog) ?? throw new NotFoundException($"The course {subject}-{catalog} does not exist.");
        var courseWithLatestVersion = await _courseRepository.GetCourseByCourseIdAndLatestVersion(course.CourseID);

        if (courseWithLatestVersion == null || courseWithLatestVersion.CourseState == CourseStateEnum.Deleted)
        {
            throw new BadRequestException($"The course {subject}-{catalog} is deleted.");
        }

        return courseWithLatestVersion;
    }

    public async Task<CourseDeletionRequest> InitiateCourseDeletion(CourseDeletionInitiationDTO deletion, Guid userId)
    {
        var oldCourse = await _courseRepository.GetCourseBySubjectAndCatalog(deletion.Subject, deletion.Catalog) ?? throw new ArgumentException("The course does not exist.");

        Dossier dossier = await _dossierService.GetDossierForUserOrThrow(deletion.DossierId, userId);

        var newDeletedCourse = Course.CloneCourseForDeletionRequest(oldCourse);

        await SaveCourseForUserOrThrow(newDeletedCourse, userId);

        var courseDeletionRequest = new CourseDeletionRequest
        {
            Id = Guid.NewGuid(),
            CourseId = newDeletedCourse.Id,
            DossierId = dossier.Id,
            Rationale = deletion.Rationale,
            ResourceImplication = deletion.ResourceImplication,
            Comment = deletion.Comment,
            Conflict = "Autogenerated comment" // TODO: Correctly autogenerate comment to indicate potential issues
        };

        await _dossierService.SaveCourseDeletionRequest(courseDeletionRequest);

        return courseDeletionRequest;
    }

    private async Task SaveCourseForUserOrThrow(Course course, Guid userId)
    {
        bool courseCreated = await _courseRepository.SaveCourse(course);
        if (!courseCreated)
        {
            throw new Exception($"Error inserting ${typeof(Course)} ${course.Id} by {typeof(User)} ${userId}");
        }
        _logger.LogInformation($"Inserted ${typeof(Course)} ${course.Id} by {typeof(User)} ${userId}");
    }

    public async Task<CourseCreationRequest?> EditCourseCreationRequest(EditCourseCreationRequestDTO edit)
    { 
        var courseCreationRequest = await _dossierService.GetCourseCreationRequest(edit.Id);

        courseCreationRequest.Rationale = edit.Rationale;
        courseCreationRequest.ResourceImplication = edit.ResourceImplication;
        courseCreationRequest.Comment = edit.Comment;
        courseCreationRequest.Conflict = "Auto-generated comment"; // TODO: Correctly autogenerate comment to indicate potential issues

        var newCourse = courseCreationRequest.NewCourse ?? throw new NotFoundException($"The course request {edit.Id} does not exist.");

        newCourse.ModifyCourseFromDTOData(edit);
        newCourse.Subject = edit.Subject;
        newCourse.Catalog = edit.Catalog;

        await _dossierRepository.UpdateCourseCreationRequest(courseCreationRequest);

        return courseCreationRequest;
    }

    public async Task<CourseModificationRequest?> EditCourseModificationRequest(EditCourseModificationRequestDTO edit)
    {
        var courseModificationRequest = await _dossierService.GetCourseModificationRequest(edit.Id);

        courseModificationRequest.Rationale = edit.Rationale;
        courseModificationRequest.ResourceImplication = edit.ResourceImplication;
        courseModificationRequest.Comment = edit.Comment;
        courseModificationRequest.Conflict = "Auto-generated comment"; // TODO: Correctly autogenerate comment to indicate potential issues

        var newCourse = courseModificationRequest.Course ?? throw new NotFoundException($"The course request {edit.Id} does not exist.");

        newCourse.ModifyCourseFromDTOData(edit);

        await _dossierRepository.UpdateCourseModificationRequest(courseModificationRequest);

        return courseModificationRequest;
    }

    public async Task DeleteCourseCreationRequest(Guid courseRequestId)
    {
        var courseCreationRequest = await _dossierService.GetCourseCreationRequest(courseRequestId);
        bool result = await _dossierRepository.DeleteCourseCreationRequest(courseCreationRequest);
        if (!result)
        {
            throw new Exception($"Error deleting ${typeof(CourseCreationRequest)} ${courseCreationRequest.Id}");
        }
        
        _logger.LogInformation($"Deleted ${typeof(CourseCreationRequest)} ${courseCreationRequest.Id}");
    }

    public async Task DeleteCourseModificationRequest(Guid courseRequestId)
    {
        var courseModificationRequest = await _dossierService.GetCourseModificationRequest(courseRequestId);
        bool result = await _dossierRepository.DeleteCourseModificationRequest(courseModificationRequest);
        if (!result)
        {
            throw new Exception($"Error deleting ${typeof(CourseModificationRequest)} ${courseModificationRequest.Id}");
        }

        _logger.LogInformation($"Deleted ${typeof(CourseModificationRequest)} ${courseModificationRequest.Id}");
    }
}
