using ConcordiaCurriculumManager.DTO.Courses;
using ConcordiaCurriculumManager.DTO.Dossiers.CourseRequests;
using ConcordiaCurriculumManager.Models.Curriculum;
using ConcordiaCurriculumManager.Models.Curriculum.Dossiers;
using ConcordiaCurriculumManager.Models.Users;
using ConcordiaCurriculumManager.Repositories;

namespace ConcordiaCurriculumManager.Services;

public interface ICourseService
{
    public IEnumerable<CourseCareerDTO> GetAllCourseCareers();
    public IEnumerable<CourseComponentDTO> GetAllCourseComponents();
    public Task<IEnumerable<string>> GetAllCourseSubjects();
    public Task<CourseCreationRequest> InitiateCourseCreation(CourseCreationInitiationDTO initiation, Guid userId);
    public Task<CourseModificationRequest> InitiateCourseModification(CourseModificationInitiationDTO modification, Guid userId);
    public Task<CourseDeletionRequest> InitiateCourseDeletion(CourseDeletionInitiationDTO deletion, Guid userId);
    public Task<Course?> GetCourseData(string subject, string catalog);
    public Task<CourseCreationRequest?> EditCourseCreationRequest(EditCourseCreationRequestDTO edit);
    public Task<CourseModificationRequest?> EditCourseModificationRequest(EditCourseModificationRequestDTO edit);
    public Task DeleteCourseCreationRequest(Guid courseRequestId);
}

public class CourseService : ICourseService
{
    private readonly ILogger<CourseService> _logger;
    private readonly ICourseRepository _courseRepository;
    private readonly IDossierService _dossierService;
    private readonly IDossierRepository _dossierRepository;

    public CourseService(ILogger<CourseService> logger, ICourseRepository courseRepository, IDossierService dossierService, IDossierRepository dossierRepository)
    {
        _logger = logger;
        _courseRepository = courseRepository;
        _dossierService = dossierService;
        _dossierRepository = dossierRepository;
    }

    public IEnumerable<CourseCareerDTO> GetAllCourseCareers()
    {
        var list = new List<CourseCareerDTO>();
        foreach (int career in Enum.GetValues(typeof(CourseCareerEnum)))
        {
            var careerEnum = (CourseCareerEnum)career;
            list.Add(new CourseCareerDTO { CareerCode = careerEnum, CareerName = careerEnum.ToString() });
        }

        return list;
    }

    public IEnumerable<CourseComponentDTO> GetAllCourseComponents()
    {
        var componentsList = new List<CourseComponentDTO>();
        foreach (var mapping in ComponentCodeMapping.GetComponentCodeMapping().ToList())
        {
            componentsList.Add(new CourseComponentDTO { ComponentCode = mapping.Key, ComponentName = mapping.Value });
        }

        return componentsList;
    }

    public async Task<IEnumerable<string>> GetAllCourseSubjects()
    {
        return await _courseRepository.GetUniqueCourseSubjects();
    }

    public async Task<CourseCreationRequest> InitiateCourseCreation(CourseCreationInitiationDTO initiation, Guid userId)
    {
        var exists = await _courseRepository.GetCourseBySubjectAndCatalog(initiation.Subject, initiation.Catalog) is not null;
        if (exists)
        {
            throw new ArgumentException("The course already exists");
        }

        Dossier dossier = await _dossierService.GetDossierForUserOrThrow(initiation.DossierId, userId);

        var course = CreateCourseFromDTOData(initiation, (await _courseRepository.GetMaxCourseId()) + 1, 1);

        await SaveCourseForUserOrThrow(course, userId);

        var courseCreationRequest = new CourseCreationRequest 
        {
            Id = Guid.NewGuid(),
            NewCourseId = course.Id,
            DossierId = dossier.Id,
            Rationale = initiation.Rationale,
            ResourceImplication = initiation.ResourceImplication,
            Comment = "Autogenerated comment" // TODO: Correctly autogenerate comment to indicate potential issues
        };

        await _dossierService.SaveCourseCreationRequest(courseCreationRequest);

        return courseCreationRequest;
    }

    public async Task<CourseModificationRequest> InitiateCourseModification(CourseModificationInitiationDTO modification, Guid userId)
    {
        var oldCourse = await _courseRepository.GetCourseByCourseId(modification.CourseId) ?? throw new ArgumentException("The course does not exist.");

        Dossier dossier = await _dossierService.GetDossierForUserOrThrow(modification.DossierId, userId);

        var newModifiedCourse = CreateCourseFromDTOData(modification, oldCourse.CourseID, oldCourse.Version + 1);

        await SaveCourseForUserOrThrow(newModifiedCourse, userId);

        var courseModificationRequest = new CourseModificationRequest
        {
            Id = Guid.NewGuid(),
            CourseId = newModifiedCourse.Id,
            DossierId = dossier.Id,
            Rationale = modification.Rationale,
            ResourceImplication = modification.ResourceImplication,
            Comment = "Autogenerated comment" // TODO: Correctly autogenerate comment to indicate potential issues
        };

        await _dossierService.SaveCourseModificationRequest(courseModificationRequest);

        return courseModificationRequest;
    }

    public async Task<Course?> GetCourseData(string subject, string catalog)
    {
        var course = await _courseRepository.GetCourseBySubjectAndCatalog(subject, catalog);
        if (course == null)
        {
            throw new ArgumentException("The course does not exist.");
        }

        var courseWithLatestVersion = await _courseRepository.GetCourseByCourseIdAndLatestVersion(course.CourseID);

        if (courseWithLatestVersion == null || courseWithLatestVersion.CourseState == CourseStateEnum.Deleted)
        {
            throw new ArgumentException("The course is deleted.");
        }

        return courseWithLatestVersion;

    }

    public async Task<CourseDeletionRequest> InitiateCourseDeletion(CourseDeletionInitiationDTO deletion, Guid userId)
    {
        var oldCourse = await _courseRepository.GetCourseByCourseId(deletion.CourseId) ?? throw new ArgumentException("The course does not exist.");

        Dossier dossier = await _dossierService.GetDossierForUserOrThrow(deletion.DossierId, userId);

        var newDeletedCourse = Course.CloneCourseForDeletionRequest(oldCourse);

        await SaveCourseForUserOrThrow(newDeletedCourse, userId);

        var courseDeletionRequest = new CourseDeletionRequest
        {
            Id = Guid.NewGuid(),
            CourseId = newDeletedCourse.Id,
            DossierId = dossier.Id,
            Rationale = deletion.Rationale,
            ResourceImplication = deletion.ResourceImplication,
            Comment = "Autogenerated comment" // TODO: Correctly autogenerate comment to indicate potential issues
        };

        await _dossierService.SaveCourseDeletionRequest(courseDeletionRequest);

        return courseDeletionRequest;
    }

    private async Task SaveCourseForUserOrThrow(Course course, Guid userId)
    {
        bool courseCreated = await _courseRepository.SaveCourse(course);
        if (!courseCreated)
        {
            _logger.LogWarning($"Error inserting ${typeof(Course)} ${course.Id} by {typeof(User)} ${userId}");
            throw new Exception("Error registering the course");
        }
        _logger.LogInformation($"Inserted ${typeof(Course)} ${course.Id} by {typeof(User)} ${userId}");
    }

    public async Task<CourseCreationRequest?> EditCourseCreationRequest(EditCourseCreationRequestDTO edit)
    { 
        var courseCreationRequest = await _dossierService.GetCourseCreationRequest(edit.Id);

        courseCreationRequest.Rationale = edit.Rationale;
        courseCreationRequest.ResourceImplication = edit.ResourceImplication;
        courseCreationRequest.Comment = "Auto-generated comment";

        var newCourse = courseCreationRequest.NewCourse ?? throw new ArgumentException("The course does not exist.");

        ModifyCourseFromDTOData(edit, newCourse);
        newCourse.Subject = edit.Subject;
        newCourse.Catalog = edit.Catalog;

        await _dossierRepository.UpdateCourseCreationRequest(courseCreationRequest);

        return courseCreationRequest;
    }

    public async Task<CourseModificationRequest?> EditCourseModificationRequest(EditCourseModificationRequestDTO edit)
    {
        var courseModificationRequest = await _dossierService.GetCourseModificationRequest(edit.Id);

        courseModificationRequest.Rationale = edit.Rationale;
        courseModificationRequest.ResourceImplication = edit.ResourceImplication;
        courseModificationRequest.Comment = "Auto-generated comment";

        var newCourse = courseModificationRequest.Course ?? throw new ArgumentException("The course does not exist.");

        ModifyCourseFromDTOData(edit, newCourse);

        await _dossierRepository.UpdateCourseModificationRequest(courseModificationRequest);

        return courseModificationRequest;
    }

    public async Task DeleteCourseCreationRequest(Guid courseRequestId)
    {
        var courseCreationRequest = await _dossierService.GetCourseCreationRequest(courseRequestId);
        bool result = await _dossierRepository.DeleteCourseCreationRequest(courseCreationRequest);
        if (!result)
        {
            _logger.LogWarning($"Error deleting ${typeof(CourseCreationRequest)} ${courseCreationRequest.Id}");
            throw new Exception("Error deleting the course creation request");
        }
        _logger.LogInformation($"Deleted ${typeof(CourseCreationRequest)} ${courseCreationRequest.Id}");
    }

    private static void ModifyCourseFromDTOData(CourseInitiationBaseDataDTO initiation, Course course)
    {
        course.Title = initiation.Title;
        course.Description = initiation.Description;
        course.CourseNotes = initiation.CourseNotes;
        course.CreditValue = initiation.CreditValue;
        course.PreReqs = initiation.PreReqs;
        course.Career = initiation.Career;
        course.EquivalentCourses = initiation.EquivalentCourses;
        course.CourseCourseComponents = CourseCourseComponent.GetComponentCodeMapping(initiation.ComponentCodes, course.Id);
        course.SupportingFiles = SupportingFile.GetSupportingFileMapping(initiation.SupportingFiles, course.Id);
    }

    private static Course CreateCourseFromDTOData(CourseRequestInitiationDTO initiation, int concordiaCourseId, int version)
    {
        var internalId = Guid.NewGuid();
        return new Course
        {
            Id = internalId,
            CourseID = concordiaCourseId,
            Subject = initiation.Subject,
            Catalog = initiation.Catalog,
            Title = initiation.Title,
            Description = initiation.Description,
            CourseNotes = initiation.CourseNotes,
            CreditValue = initiation.CreditValue,
            PreReqs = initiation.PreReqs,
            Career = initiation.Career,
            EquivalentCourses = initiation.EquivalentCourses,
            CourseState = initiation.GetAssociatedCourseState(),
            Version = version,
            Published = false,
            CourseCourseComponents = CourseCourseComponent.GetComponentCodeMapping(initiation.ComponentCodes, internalId),
            SupportingFiles = SupportingFile.GetSupportingFileMapping(initiation.SupportingFiles, internalId)
        };
    }
}
