export enum BaseRoutes {
    Home = "/",
    Login = "/login",
    Register = "/register",
    Dossiers = "/dossiers",
    NotFound = "*",
    AddCourse = "/add-course",
    ComponentsList = "/components-list",
    CourseBrowser = "/CourseBrowser",
    ManageableGroup = "/manageablegroup",
    Groups = "/groups",
    CreateGroup = "/creategroup",
    AddUserToGroup = "/addusertogroup",
    RemoveUserFromGroup = "/removeuserfromgroup",
    DossierDetails = "/dossierdetails/:dossierId",
}
