name: Backend Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'Server/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore Server/ConcordiaCurriculumManager/ConcordiaCurriculumManager.csproj

    - name: Run backend tests
      run: dotnet test Server/ConcordiaCurriculumManagerTest/ConcordiaCurriculumManagerTest.csproj