name: Frontend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'App/**'
  pull_request:
    paths:
      - 'App/**'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --prefix App

    - name: Run ESLint
      run: npm run lint --prefix App

    - name: Run frontend tests
      run: npm test --prefix App
  
  deploy-frontend:
    needs:
    - frontend-tests
    if: github.ref == 'refs/heads/main' && needs.frontend-tests.result == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env:
        deploy_url: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}
      run: |
          curl "$deploy_url"